### ISSUE TITLE
핵심 기술

### ISSUE THREAD

**Issue by changukang** [kupl/kaprese#3]
Kaprese 도구에 포함된 기술들과 그 설명은 어디서 찾아 볼 수 있나요?

**Comment by henrylee97** [comment]
현재 Kaprese 도구에 포함된 기술은 아래 표와 같습니다:
| Engines | Repository                                               |
| :------ | :------------------------------------------------------- |
| `saver` | [kupl/SAVER_pubic](https://github.com/kupl/Saver_public) |
| `cafe`  | [kupl/LearnML](https://github.com/kupl/LearnML)          |

이 내용은 #45가 머지되면 `README.md` 에서 찾아 볼 수 있고, 지속적으로 업데이트 될 예정입니다.
