### ISSUE TITLE
Print "Not supported" in gray color instead of red

### ISSUE THREAD

**Issue by seongjoonh** [kupl/kaprese#38]
https://github.com/kupl/kaprese/blob/8f20ca40930f671ce145eed09b8828c7c75bded7/kaprese/bin/kaprese_run.py#L65

Gray seems more fitting than the current red for "Not supported" message in the status output?
It also aligns well with 'n\a'.

**Comment by henrylee97** [comment]
Thank you.
This issue will be closed when #39 is merged.
