### ISSUE TITLE
벤치마크

### ISSUE THREAD

**Issue by changukang** [kupl/kaprese#4]
벤치마크에 관한 통계(개수, 종류, 출처 등)는 어디서 찾아볼 수 있나요.

**Comment by henrylee97** [comment]
벤치마크의 통계는 직접 제공하지 않습니다.
포함되어 있는 벤치마크의 출처는 아래의 표와 같습니다:
| Benchmarks | Repository                                                                                |
| :--------- | :---------------------------------------------------------------------------------------- |
| `c`        | C benchmarks in [kupl/starlab-benchmarks](https://github.com/kupl/starlab-benchmarks)     |
| `ocaml`    | OCaml benchmarks in [kupl/starlab-benchmarks](https://github.com/kupl/starlab-benchmarks) |

위 내용은 #45가 머지되면 `README.md`에서 찾아 볼 수 있고, 지속적으로 업데이트 될 예정입니다.
