### ISSUE TITLE
기술 입출력

### ISSUE THREAD

**Issue by changukang** [kupl/kaprese#5]
Kaprese 도구를 돌리기 위해 사용자는 무엇을 명세해야 하며,
그로부터 출력되는 결과값들은 무엇무엇이 확인될 수 있는건가요.

**Comment by marinelay** [comment]
README.md에 Add Benchmark Section을 참조하면 될 것 같습니다.
출력되는 결과 값은 Repair가 되었는지 유무와 시간이 출력됩니다.
