### ISSUE TITLE
2차 저작권

### ISSUE THREAD

**Issue by changukang** [kupl/kaprese#6]
kaprese를 제 연구 혹은 소프트웨어 관리 도구로 사용하고 싶습니다.
이에대한 저작권 규정이 무엇인가요?

**Comment by henrylee97** [comment]
`kaprese`는 MIT 라이선스를 통해 배포되고 있습니다.
자세한 내용은 아래 파일을 참고해주세요.
https://github.com/kupl/kaprese/blob/main/LICENSE
